site_name: Ai and sustainability
nav:
  - Home: index.md
  - 1st session: 1stsession.md 
  - Papers: papers.md
  - Applications: applications.md
  - Assignment n째1: 'Assignment_1.md'
  - Assignment n째2: 'Assignment_2.md'
  - Assignment n째3: 'Assignment_3.md'
  - Assignment n째4: 'Assignment_4.md'
  - Final Presentation: 'FinalPresentation.md'
  - Facts and Values: 'facts&values.md'
theme: readthedocs
markdown_extensions:
  - footnotes
