site_name: Ai and sustainability
nav:
  - Home: index.md
  - 1st session: 1stsession.md 
  - Papers: papers.md
  - Applications: applications.md
  - Assignment n°1: 'Assignment n°1.md'
  - Facts and Values: 'facts&values.md'
theme: readthedocs